### ISSUE TITLE
How to catch the case where the solver doesn't converge?

### ISSUE THREAD

**Issue by xavier-alexandre** [bcc-research/CFMMRouter.jl#27]
In the case where the solver can't converge, we can somehow detect it via the `verbose` flag:
`CFMMRouter.route!(router, verbose=(verbose == "true")`

But the solver would still output results, that are wrong. Is there a way to catch programmatically the fact that convergence couldn't be achieved, instead?

**Comment by angeris** [comment]
For now, as a current workaround, you should check the optimality conditions! We're currently finding a longer fix for this, since the `lbfgsb` interface is unfortunately quite not clean. On the other hand, you can look at the struct itself and parse some of the returned conditions, but it's a bit of a pain as well.
